# This rule is not used by the project hdfs-crd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to hdfscrd.fatihmete.github.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hdfs-crd
    app.kubernetes.io/managed-by: kustomize
  name: hdfscluster-viewer-role
rules:
- apiGroups:
  - hdfscrd.fatihmete.github.io
  resources:
  - hdfsclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hdfscrd.fatihmete.github.io
  resources:
  - hdfsclusters/status
  verbs:
  - get
